### ISSUE TITLE
Add your name

### ISSUE THREAD

**Issue by christina-ml** [JoseBorbon/Yu-Gi-Oh-TCG#3]
Add your name to the README file.

**Comment by JoseBorbon** [comment]
If anyone is interested in participating add your name and look for ways to contribute. This is a free for all kinda thing and we got a big to do list so if you guys see something you like, definitely let me know.

**Comment by JoseBorbon** [comment]
Good Job Everyone, onboarding and getting people up to speed was a little rough but overall we did good. Keep up the great work, I believe in you all and we're GR8.0.
